MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = "huynhdaihuybank3@gmail.com"
MAIL_PASSWORD = "qsvu wkza zjnm svik"
MAIL_DEFAULT_SENDER = "huynhdaihuybank3@gmail.com"
MAIL_PASSWORD = "qsvu wkza zjnm svik"

SECRET_KEY = "BLACKISM_ONODAMICHI_ACCESS_TOKEN"
REFRESH_SECRET_KEY = "BLACKISM_ONODAMICHI_REFRESH_TOKEN"
EMAIL_VERIFICATION_SECRET_KEY="BLACKISM_ONODAMICHI_EMAIL_TOKEN"

CLOUDYNARY_SECRET_KEY= "DeDNByB65KKHtk9XGTrJid-Zxyw"
CLOUDYNARY_API_KEY= "318882938114629"
CLOUDYNARY_CLOUD_NAME= "dtqwnqfrq"

